name: First workflow

on:
  workflow_dispatch:
  
jobs:
  firstjob:
    runs-on: self-hosted
    steps:
     - name: firstjob script
       shell: bash
       run: echo Hello world
     - uses: actions/checkout@v3
     
        
  
