name: second workflow with github hosted ruuner

on:
  workflow_dispatch:

jobs:
  firstjob:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - shell: bash
        run: echo Job Completed
      
     
    
    
   
